### ISSUE TITLE
优先队列里面代码里面没有继承的Queue对象的具体代码

### ISSUE THREAD

**Issue by liyangIsDSG** [XPoet/js-data-structures-and-algorithms#13]
希望贴一下Queue的代码

**Comment by dragon-liu** [comment]
可以参考我的项目，里面有队列各种实现：https://github.com/dragon-liu/javascript-datastructures-algorithms

**Comment by dragon-liu** [comment]
> 希望贴一下Queue的代码

可以参考我的项目，里面有队列各种实现：https://github.com/dragon-liu/javascript-datastructures-algorithms

**Comment by XPoet** [comment]
@liyangIsDSG 

队列：
https://github.com/XPoet/js-data-structures-and-algorithms/blob/master/src/Queue/queue.js

优先队列：
https://github.com/XPoet/js-data-structures-and-algorithms/blob/master/src/PriorityQueue/priorityQueue.js
