### ISSUE TITLE
数组的第一篇就错了

### ISSUE THREAD

**Issue by huanggengzhong** [XPoet/js-data-structures-and-algorithms#4]
let myArray2 = [1, 2, 3, 4, 5];
// 删除索引 4 位置起，2 个元素
myArray2.splice(4, 2);
console.log(myArray2); //--> [1, 2, 3,4],你写成了[1,2,3]

**Comment by XPoet** [comment]
感谢指正

**Comment by XPoet** [comment]
文章已更正，该 Issue 关闭
